
import javax.swing.JOptionPane;


/**
 *
 * @author janle
 */
public class InputForm extends javax.swing.JFrame {

    /**
     * Creates new form InputForm
     */
    public InputForm() {
        initComponents();
        errorMsg.setVisible(false);
        FileEditor.initializeFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddButton = new javax.swing.JButton();
        amountTextField = new javax.swing.JTextField();
        categoriesDropdown = new javax.swing.JComboBox<>();
        errorMsg = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        expensesScreenBtn = new javax.swing.JButton();
        overviewScreenBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(18, 50, 62));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(18, 50, 62));

        AddButton.setBackground(new java.awt.Color(71, 223, 156));
        AddButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddButton.setText("Hinzufügen");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        amountTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        amountTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountTextField.setText("0.0");
        amountTextField.setToolTipText("");
        amountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextFieldActionPerformed(evt);
            }
        });
        amountTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountTextFieldKeyTyped(evt);
            }
        });

        categoriesDropdown.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        categoriesDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lebensmittel", "Wohnen", "Transport", "Gesundheit", "Bildung", "Unterhaltung", "Sonstiges" }));

        errorMsg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(255, 0, 51));
        errorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMsg.setText("Ungültige Eingabe");

        title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(71, 223, 156));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Ausgabe erfassen");

        expensesScreenBtn.setBackground(new java.awt.Color(71, 223, 156));
        expensesScreenBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        expensesScreenBtn.setText("Erfassen");
        expensesScreenBtn.setPreferredSize(new java.awt.Dimension(341, 32));
        expensesScreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expensesScreenBtnActionPerformed(evt);
            }
        });

        overviewScreenBtn.setBackground(new java.awt.Color(71, 223, 156));
        overviewScreenBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        overviewScreenBtn.setText("Bericht");
        overviewScreenBtn.setPreferredSize(new java.awt.Dimension(341, 32));
        overviewScreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewScreenBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amountTextField)
                            .addComponent(categoriesDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(264, 264, 264))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(expensesScreenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(overviewScreenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(categoriesDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(errorMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expensesScreenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overviewScreenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(title)
                    .addContainerGap(375, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try {
            float inputAmount = Float.parseFloat(amountTextField.getText());
            String inputCategory = categoriesDropdown.getSelectedItem().toString();
            if (inputAmount != 0.0) {
                FileEditor.addARecord(inputAmount, inputCategory);
                errorMsg.setVisible(false);
                JOptionPane.showMessageDialog(this, "Ausgabe erfolgreich hinzugefügt.");
            }
        } catch (Exception e) {
            errorMsg.setVisible(true);
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void amountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextFieldActionPerformed

    }//GEN-LAST:event_amountTextFieldActionPerformed

    private void amountTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTextFieldKeyTyped
        char enteredCharacter = evt.getKeyChar();

        if (!Character.isDigit(enteredCharacter) && enteredCharacter != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_amountTextFieldKeyTyped

    private void expensesScreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expensesScreenBtnActionPerformed

    }//GEN-LAST:event_expensesScreenBtnActionPerformed

    private void overviewScreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewScreenBtnActionPerformed
        dispose();
        new OverviewForm().setVisible(true);
    }//GEN-LAST:event_overviewScreenBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JComboBox<String> categoriesDropdown;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JButton expensesScreenBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton overviewScreenBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
